import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/styles/header.scss";
import "../assets/styles/main.scss";
import "./globals.css";
import Header from "./layouts/header";
import Footer from "./layouts/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>{children}</body>
      <Footer />
    </html>
  );
}
